### ISSUE TITLE
Cannot install recent AECU on AEM 6.5

### ISSUE THREAD

**Issue by pun-ky** [valtech/aem-easy-content-upgrade#106]
bundle hangs on installed state

`org.apache.sling.xss,version=[1.2,2) -- Cannot be resolved`

in readme you mentioned

> AECU requires Java 8 and AEM 6.3 or above.

:/

**Comment by pun-ky** [comment]
Bump 😉

Any chance to get it working / released version working with 6.5?

**Comment by gruberrolandvaltech** [comment]
Thanks for the reminder. ;-) We plan to release within one week.

**Comment by gruberrolandvaltech** [comment]
Updated documentation on aecu_2.0 branch.

**Comment by pun-ky** [comment]
thx, tested, works properly
