### ISSUE TITLE
Add to printProperty() capability to print arrays. 

### ISSUE THREAD

**Issue by roxana-muresan** [valtech/aem-easy-content-upgrade#113]
At the moment printProperty() called on a multivalue property prints the object toString. A pretty print of the arrays' elements should be returned.

**Comment by gruberrolandvaltech** [comment]
`aecu
    .contentUpgradeBuilder()
        .forResources((String[])["/content/cq:tags"])
        .printProperty("jcr:mixinTypes")
        .run()`

**Comment by roxana-muresan** [comment]
Here's an output example: 
Running content upgrade DRY...
jcr:mixinTypes = [Ljava.lang.String;@760a3add
