### ISSUE TITLE
Force property value

### ISSUE THREAD

**Issue by TheDoc42** [valtech/aem-easy-content-upgrade#125]
Hello,
during my last project (on AECU 1.8.1), I ran into the issue of setting a property value when the value's type change

@description: (String[])["old desc"]

to 

@description: (String) "new description"

This would fail with setProperty on an Exception because of the change from isMultiple from true to false (or the opposite)

Could be replaced by 
.doDeletePropery().setProperty()

if we mention it is the documentation or in a "recipe book"?
The solution is a bit counterintuitive.

**Comment by TheDoc42** [comment]
I did prepare a local branch for a pull request with the proposed change but I cannot seem to upload it to the repositiory.

Cheers,
yves.debruyne@valtech.com (Valtech CH)

**Comment by gruberrolandvaltech** [comment]
You need to fork the project. Then you can create the PR in your local project.

**Comment by gruberrolandvaltech** [comment]
Closing as there is no progress here and there are issues with the internal node caching that interfere with the type change.
