### ISSUE TITLE
Flatten property

### ISSUE THREAD

**Issue by TheDoc42** [valtech/aem-easy-content-upgrade#127]
When saving a property in AEM, missing hints (or strange bevavior of dialogs?) can result in a same field to be stored in different Formats. (Array vs one Object)

I would propose a doFlattenStringProperty("name") that whould switch a field from a multi-valued field into a single value field.

doFlattenStringProperty(name, ",")
@name: (String[])["hello"] -> @name="hello"
@name: (String[])["hello", "goodbye"] -> @name="hello,goodbye"
@name: (String[])[] -> @name=""

If the value is not multivalued we leave the field as is
If the value does not exist we ignore the command 

I'm not sure what I would propose for other types.
Alternatives:

doFlattenProperty(name)
if (multiValued) {
  if (values.length==1) {
    //force single value property
    return
  }
  if (values.length==0) {
    //what value should we set? if we set null the property disappears...
    return
  }
  //throw error
}

Or should we keep this code to customHandlers and let each project decide?

(can try to provide code example after discussion)

**Comment by TheDoc42** [comment]
Easy solution after a night's sleep

doFlattenProperty(name, emptyValue)

**Comment by roxana-muresan** [comment]
HI @TheDoc42! I find the word "flatten" not that explanatory. "join" would be a more popular word for transforming arrays into one value. doJoinMultivalueProperty

**Comment by TheDoc42** [comment]
Good idea, will change the code accordingly

**Comment by TheDoc42** [comment]
Renaming the function to join was a good idea. The code logic cleaned up a bit.

I added 3 functions to the API, but I'm not sure if the fallback versions are needed.
I tried adding them to the Readme and it just turned out messy...

doJoinProperty(name, separator, fallback)

(the alternates read:
doJoinProperty(name) - separator: ","; fallback: null
doJoinProperty(name, fallback) - separator: ","
)
