### ISSUE TITLE
Support recent Groovy Console

### ISSUE THREAD

**Issue by pun-ky** [valtech/aem-easy-content-upgrade#135]
![image](https://user-images.githubusercontent.com/10673561/85275484-b09b4200-b480-11ea-8c9f-12906b538431.png)

ASAP fix would be very appreciated.

**Comment by gruberrolandvaltech** [comment]
This is blocked by https://github.com/icfnext/aem-groovy-console/issues/107

**Comment by pun-ky** [comment]
ok, but the plan is...? :)

**Comment by pun-ky** [comment]
This is rather an incompatibility occurring in AEM versions in range [6.4.5,6.5).
So if you will consider AEM version >= 6.5 you should be able to release AECU supporting it.
Then when the fix for this exceptional range will be available you could release the AECU again supporting this too.

**Comment by gruberrolandvaltech** [comment]
Version 16.0.0 has the same issue. Probably, we will release AECU 3.2 with Groovy Console 14 first. Afterwards, we can switch to 16.0.0 and AEM >= 6.5.
There are also some API changes in Groovy Console that need to be adapted in AECU (https://github.com/valtech/aem-easy-content-upgrade/pull/132).

**Comment by pun-ky** [comment]
About api changes.. That's an impact of my other request. Sorry 😁

**Comment by gruberrolandvaltech** [comment]
Merged to develop
