### ISSUE TITLE
New tags can't be added to the Healthchecks

### ISSUE THREAD

**Issue by pcastelog** [valtech/aem-easy-content-upgrade#151]
Hi,

I'm using version 3.2.0 (and already check with 4.0.0) and I want to change the tags for the healthcheck to be able to them in different scopes. 
I want to check the "Last Run Check" as post-deployment step to check that all scripts were executed properly and the "AECU Self Check" during the deployment to make sure that AECU package was installed properly.
Is there any option already in place to be able to modify those tags?

Thanks,

**Comment by gruberrolandvaltech** [comment]
You can use the tag "aecu-last-run" with next release. For the moment you can just use "aecu" which does more checks but does not harm and is fast.

To add the AECU check in your custom health tag please use composite health tags: https://adobe-consulting-services.github.io/acs-aem-tools/features/healthchecks/index.html

**Comment by pcastelog** [comment]
First of all, thank you for the change.

The approach that I'm following for the moment is to use the "aecu" tag in both checks.
