### ISSUE TITLE
CQRules:CQBP-84 critical issue with the CloudManager last released version

### ISSUE THREAD

**Issue by silvamiguelez** [valtech/aem-easy-content-upgrade#156]
Since the last Cloud Manager version release (just today) I think that all customers using aecu could be experiencing Sonar critical issues that could break their builds:

Here the Cloud Manager aecu related log entries: 

- The product interface org.apache.sling.api.SlingHttpServletRequest annotated with @ProviderType should not be implemented by custom code. Detected in de.valtech.aecu.core.service.GroovyConsoleRequest contained in /apps/valtech/aecu/install/aecu.core-4.0.0.jar (Critical) - CQRules:CQBP-84

- The product interface org.apache.sling.api.SlingHttpServletResponse annotated with @ProviderType should not be implemented by custom code. Detected in de.valtech.aecu.core.service.GroovyConsoleResponse contained in /apps/valtech/aecu/install/aecu.core-4.0.0.jar (Critical) - CQRules:CQBP-84

And some related adobe docs about the CQRule: https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/using/how-to-use/custom-code-quality-rules.html?lang=en#product-apis-annotated-with-providertype-should-not-be-implemented-or-extended-by-customers

**Comment by gruberrolandvaltech** [comment]
This was fixed and is planned to be published today.
