### ISSUE TITLE
Incorrect primaryType nt:folder in /apps/cq/core/content/nav/tools/aecu causes conflict

### ISSUE THREAD

**Issue by senn** [valtech/aem-easy-content-upgrade#168]
When calling a code-quality pipeline on our AEMaaCS project that uses `aecu.complete.cloud` the Build Images step throws the following error:

`Caused by: javax.jcr.nodetype.ConstraintViolationException: OakConstraint0001: /apps/cq/core/content/nav/tools[[nt:folder]]: No matching definition found for child node general with effective type [nt:unstructured]`

This is caused by AECU installing the entire path `/apps/cq/core/content/nav/tools/aecu` as `nt:folder` types.  
This causes conflicts with other libraries (like Composum Nodes) that also use the path `/apps/cq/core/content/nav/tools`.

We tried circumventing this by providing install order but without success.

Workaround: remove AECU from our project

**Comment by senn** [comment]
Some updates: we also tried providing the path using our ui.apps.structure project (see https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/developing/repository-structure-package.html?lang=en) but without success. 

We did however manage to get this working by creating a RepoInit script that pre-creates the `/apps/cq/core/content/nav/tools` path.

```
scripts=["
    create path (sling:Folder) /apps/cq/core/content/nav/tools
"]
```

**Comment by gruberrolandvaltech** [comment]
Will be fixed in next release
