### ISSUE TITLE
AEM as a cloud - author instance - missing bindings

### ISSUE THREAD

**Issue by michal-tobiasz-wttech** [valtech/aem-easy-content-upgrade#190]
I have executed deploy on the cloud using version 6.0.2 and unfortunately the first of two author instances had the same issue with missing bindings. The second Author instance didn't have an issue. I didn't have time to run more deploys but I would assume it is possible that during deployment all Author instances can have this issue.
Attaching log: 
[issue.log](https://github.com/valtech/aem-easy-content-upgrade/files/8835739/issue.log)

**Comment by gruberrolandvaltech** [comment]
Thanks a lot for the log. We will check how this can be handled.

**Comment by gruberrolandvaltech** [comment]
Can you check if there is anything in the logs when "de.valtech.aecu.startuphook.AecuCloudStartupService" was registered? It would be interesting to know what happened between the registration and the actual start of the scripts.

**Comment by michal-tobiasz-wttech** [comment]
Attaching logs from "de.valtech.aecu.startuphook.AecuCloudStartupService" registration to migration start
[aecu-cloud-startup-service-registration.log](https://github.com/valtech/aem-easy-content-upgrade/files/8856464/aecu-cloud-startup-service-registration.log)
