### ISSUE TITLE
AEM as a cloud - author instance - missing bindings

### ISSUE THREAD

**Issue by michal-tobiasz-wttech** [valtech/aem-easy-content-upgrade#192]
Unfortunately,  today after the fifth execution of the deployment on Cloud Manager, the issue occurred.
```
21.06.2022 11:44:47.064 [cm-p29439-e93903-aem-author-7ddd5dccff-xr5zx] *ERROR* [Thread-100] com.icfolson.aem.groovy.console.impl.DefaultGroovyConsoleService error running script
groovy.lang.MissingPropertyException: No such property: aecu for class: Script1
```
```
21.06.2022 11:44:47.891 [cm-p29439-e93903-aem-author-7ddd5dccff-xr5zx] *INFO* [Thread-100] de.valtech.aecu.core.service.AecuServiceImpl Executing script /apps/aecu-scripts/test/five-thousand-pages-test/1-pages-modification-long-script.groovy
groovy.lang.MissingMethodException: No signature of method: Script1.getResource() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [/var/aecu-installhook/1-pages-modification-long-script]
	at de.valtech.aecu.core.service.AecuServiceImpl.executeScript(AecuServiceImpl.java:209) [de.valtech.aecu.core:6.0.3]
```
Attaching logs from today's deployment
[author_aemerror_2022-06-21.zip](https://github.com/valtech/aem-easy-content-upgrade/files/8952399/author_aemerror_2022-06-21.zip)

**Comment by gruberrolandvaltech** [comment]
I guess this is caused by the Sling pipes actions you have before. Looks like this delays the startup and therefore causes the issue.
Can you run the Sling pipes actions after startup? E.g. AECU starts a separate thread for the migration to not block the @Activate method.

**Comment by michal-tobiasz-wttech** [comment]
Ok, I will turn off the execution of Sling pipes and do more deployments to be sure that everything works fine in case of groovy execution. 
I will keep you updated

**Comment by michal-tobiasz-wttech** [comment]
I can confirm that Sling pipes could cause issues with bindings for the latest version of AECU. 
I have turned off the Sling pipes and executed about 10 deployments and non of them had an issue. Thank you for your help!
