### ISSUE TITLE
mvn install does not seem to work for cloud

### ISSUE THREAD

**Issue by nutmix** [valtech/aem-easy-content-upgrade#198]
Get this error:

[^[[1;33mWARNING^[[m] 'dependencyManagement.dependencies.dependency.version' for de.valtech.aecu:aecu.complete.cloud:zip is either LATEST or RELEASE (both of them are being deprecated) @ line 715, column 22

When added flowing to the root pom.xml:

        <dependency>
            <groupId>de.valtech.aecu</groupId>
            <artifactId>aecu.complete.cloud</artifactId>
            <version>LATEST</version>
            <type>zip</type>
        </dependency>

% mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven
Java version: 11.0.10, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "12.5.1", arch: "aarch64", family: "mac"

trying to install with this command:

 % mvn clean install  -PautoInstallSinglePackageAuthor

When we login to author after the build, there is no groovy console on http://localhost:4502/groovyconsole (gives: Resource at '/groovyconsole' not found: No resource found), and there is no aem update console in author admin.

**Comment by nutmix** [comment]
Someone has said that mvn does not download the package, and that this has to be done manually.  If so, where and how does one install the package?

**Comment by bdhoine** [comment]
here it's working fine in cloud and cloud sdk by following the documentation and embedding the package, did you embed the aecu zip in the all package?

**Comment by gruberrolandvaltech** [comment]
There is no Maven profile "autoInstallSinglePackageAuthor". Please use "autoInstallPackage" in the right "complete" project after building with "clean install".

In general, installation should be done by embedding AECU in your application complete package. The Maven commands are only for AECU development. No need to clone the project as all versions are on Maven Central.
