### ISSUE TITLE
Release date for 6.2.0

### ISSUE THREAD

**Issue by Altenfrost** [valtech/aem-easy-content-upgrade#203]
Hi,
Is there any exact date for release 6.2.0? Are there plans to release it in the near future? 
My company is very much looking forward to the changes made with the improving groovy console https://github.com/valtech/aem-easy-content-upgrade/pull/200

Thanks in advance for the response.

**Comment by gruberrolandvaltech** [comment]
We are blocked by ongoing server issues at Maven Central that make it impossible for most projects to perform a release.
Will provide an update as soon as this changes.

**Comment by gruberrolandvaltech** [comment]
The release finally worked. It should be on Maven Central in about 15min.

**Comment by royteeuwen** [comment]
When upgrading, dont forget to rename your OSGi config for Groovy console to:

be.orbinson.aem.groovy.console.configuration.impl.DefaultConfigurationService.cfg.json

Maybe something you can mention in the release notes @gruberrolandvaltech ?

**Comment by gruberrolandvaltech** [comment]
Thanks, notes updated. 👍
