### ISSUE TITLE
AEMaaCS: You are not allowed to execute scripts

### ISSUE THREAD

**Issue by aguacatedan** [valtech/aem-easy-content-upgrade#224]
Hello, 

I see this error showing up in red letters when I go to Tools > AEM Easy Content Upgrade > Execute. I'm a admin in AEM.
I also tried browsing to the path where the scripts are but it doesn't even show them.

This quite strange because I was able to execute scripts manually before, maybe a week ago or so. Is there a specific permission I need to check for?

AEM Release: 2023.10.14029.20231020T111912Z
AECU version: 6.4.0
Path used for groovy scripts: /apps/aecu-scripts

**Comment by nhirrle** [comment]
Hello

This is indeed strange. I am not aware of any issue. Are you still experiencing any issues? 
Does it work without AECU, just Groovyconsole directly? If not you can actually also raise a ticket in https://github.com/orbinson/aem-groovy-console as this is the team maintaining the groovy console code. AECU just embeds it and adds functionality on top.

**Comment by nhirrle** [comment]
And please check if it works with the Cloud SDK. And in Groovyconsole you will need to add the OSGi Configuration which groups are allowed to execute groovyscripts: https://github.com/orbinson/aem-groovy-console#osgi-configuration / Script Execution Allowed Groups . Please verify that your user is assigned to one of the groups

**Comment by nhirrle** [comment]
As there was no response on the ticket, I assume one of the tips above helped. 
Feel free to reopen or create a new issue if the issue persist
