### ISSUE TITLE
aecu.ui.content overwrites the configured weekly operations window

### ISSUE THREAD

**Issue by kwin** [valtech/aem-easy-content-upgrade#225]
Due to the filter rule https://github.com/valtech/aem-easy-content-upgrade/blob/891f68c7aabed3c8ad54c57fe749508f8bd1bc83/ui.content/src/main/content/META-INF/vault/filter.xml#L4 any customization to the weekly maintenance window is overwritten with each installation of the package

**Comment by kwin** [comment]
Also this should rather be located in `/apps/settings` (https://experienceleague.adobe.com/docs/experience-manager-65/administering/introduction/configurations.html?lang=en#configuration-resolution) as `/conf` is really supposed to be used by admins with the Web UI only. One can easily disable a task configured in `/apps/settings/granite/operations/maintenance/granite_weekly` in the UI (this will create an override in `/conf/global/settings/....` which hides the task resource).

**Comment by nhirrle** [comment]
Thanks @kwin ! Also for the Pull Request to fix this.
