### ISSUE TITLE
Warnings on Readiness and Best Practice Analyzer

### ISSUE THREAD

**Issue by pcastelog** [valtech/aem-easy-content-upgrade#230]
Evaluating the move to cloud, some warnings appeared in the report (https://experienceleague.adobe.com/en/docs/experience-manager-learn/cloud-service/migration/cloud-acceleration-manager/readiness-and-best-practice-analyzer)

- /oak:index/aecuHistory-custom-1,The /oak:index/aecuHistory-custom-1 Oak index has a rule violation: reindex property is not allowed
- /oak:index/aecuHistory-custom-1,The /oak:index/aecuHistory-custom-1 Oak index has a rule violation: seed property is not allowed

The second one I believe is an bug on the tool since can't find the property in https://github.com/valtech/aem-easy-content-upgrade/blob/develop/oak.index/src/main/content/jcr_root/_oak_index/aecuHistory-custom-1/.content.xml 

Also, I see that after v.5.0.0 the oak:index was moved from /var/aecu but never removed programmatically, since the tool also found

- /var/aecu/oak:index/aecuHistory,The /var/aecu/oak:index/aecuHistory Oak index has a rule violation: Custom definition name must follow the pattern <name>-custom-<version>
- /var/aecu/oak:index/aecuHistory,The /var/aecu/oak:index/aecuHistory Oak index has a rule violation: Path must begin with /oak:/index
- /var/aecu/oak:index/aecuHistory,The /var/aecu/oak:index/aecuHistory Oak index has a rule violation: reindex property is not allowed
- /var/aecu/oak:index/aecuHistory,The /var/aecu/oak:index/aecuHistory Oak index has a rule violation: seed property is not allowed

**Comment by pcastelog** [comment]
https://github.com/valtech/aem-easy-content-upgrade/pull/231

**Comment by nhirrle** [comment]
hi @pcastelog 
Just released 6.5.1 - can we close the case?
