### ISSUE TITLE
AECU prevents execution of correctly configured cloud maintenance tasks.

### ISSUE THREAD

**Issue by BertDL** [valtech/aem-easy-content-upgrade#235]
When configuring granite_weekly tasks in AEM cloud under /apps/settings/granite/operation/maintenance/granite_weekly, the repoinit script of AECU blocks the correct working of the granite_weekly script.
The repo script creates a folder in /conf/global/settings/granite/operations/maintenance/granite_weekly without the correct properties. This means the /conf/global/settings/granite/operations/maintenance/granite_weekly is not executed, but also it blocks other valid configs in apps as there is no inherit property set on the node.

Please remove 
    create path /conf/global/settings/granite(nt:folder)
    create path /conf/global/settings/granite/operations(nt:folder)
    create path /conf/global/settings/granite/operations/maintenance(sling:OrderedFolder)
    create path /conf/global/settings/granite/operations/maintenance/granite_weekly(sling:OrderedFolder)
from the complete-cloud/src/main/content/jcr_root/apps/valtech/aecu-complete/config/org.apache.sling.jcr.repoinit.RepositoryInitializer~setacls.config config as the AECU purge configuration is now located in /apps

**Comment by nhirrle** [comment]
thanks @BertDL , fixed and deployed a new version
