### ISSUE TITLE
Groovy closure processing

### ISSUE THREAD

**Issue by 3xil3** [valtech/aem-easy-content-upgrade#28]
I'm not entirely sure if it's actually possible within the current groovy binding implementation, but ultimate flexibility could be achieved if there were an option to pass in a groovy closure `{ [closureParameters -> ] statements }` to the builder. 

This would allow to apply very custom logic to process the resources while staying with the comfort of the builder. 

Something along the lines of:

```java
aecu.contentUpgradeBuilder().forResources((String[])["/content/we-retail/ca/en"])
.process({item -> 
    def obj=item.adaptTo(MyCustomClazz.class)
    if(obj.category ==5 || obj.category ==8) {
      // do more custom migration stuff
    }
}).run()
```

**Comment by gruberrolandvaltech** [comment]
Good point, we will add that. 👍

**Comment by gruberrolandvaltech** [comment]
Will be in 1.5
