### ISSUE TITLE
Code completion in binding

### ISSUE THREAD

**Issue by gruberrolandvaltech** [valtech/aem-easy-content-upgrade#55]
The Groovy Console already uses a JS library for syntax highlighting. This also supports code completion. We should use it for our aecu binding.

**Comment by gruberrolandvaltech** [comment]
The used lib is ACE:
https://github.com/ajaxorg/ace
https://ace.c9.io/

**Comment by Vizz85** [comment]
useful links:
https://gist.github.com/oskude/b760606d6842b498d018dc0bc27d3593

**Comment by gruberrolandvaltech** [comment]
Depends on https://github.com/valtech/aem-easy-content-upgrade/pull/84

**Comment by gruberrolandvaltech** [comment]
Autocompletion examples:

https://gist.github.com/yuvalherziger/aa48782568c6914b55066d290ff88360
http://plnkr.co/edit/6MVntVmXYUbjR0DI82Cr?p=preview

**Comment by gruberrolandvaltech** [comment]
lang-tools is in /etc/clientlibs/groovyconsole/js/ext-language_tools.js
