### ISSUE TITLE
Directory level fallback scripts

### ISSUE THREAD

**Issue by gruberrolandvaltech** [valtech/aem-easy-content-upgrade#63]
In addition to define file level fallback scripts it would be great to have them on directory level. This could be used to e.g. install a backup.

File name should be "fallback.groovy".

**Comment by gruberrolandvaltech** [comment]
Managed by https://github.com/valtech/aem-easy-content-upgrade/pull/85

**Comment by roxana-muresan** [comment]
Tested and merged
