### ISSUE TITLE
Be able to specify script constraints 

### ISSUE THREAD

**Issue by pun-ky** [valtech/aem-easy-content-upgrade#79]
Final decision:

Script naming:

 - prechecks.groovy
 - script1.prechecks.groovy
 - script1.groovy
 - script2.groovy
 - script3.groovy

prechecks.groovy would be the default for the whole folder.
script1.prechecks.groovy would override the default for script1.groovy.
Prechecks are optional. If no such script exists then execution will be as before.

-----------------------------

For instance, I'd like to have an ability to implement Groovy Script that is executable only, if currently deployed CRX Package -> OSGi bundle has at least x.x.x version. This will protect against runtime execution errors and provide a way for implementing scripts earlier, that will be executed later automatically (if constraint will met).

What do you think about that feature? Could you consider implementing this / addressing somehow?

**Comment by pun-ky** [comment]
Imports must be at the beginning of the script so that this is not realizable 😉

**Comment by gruberrolandvaltech** [comment]
Yes, but the imports should not do any harm. They can be executed in any case as long as the import does not depend on the tested bundle, does it?

**Comment by pun-ky** [comment]
They will depend. That's the case exactly.

I am thinking about 

Sample.groovy and Sample.constraint.groovy 

Aecu firstly executes constraint. If it is ok / return true executes main script with no classifier.

What do you think.?

**Comment by pun-ky** [comment]
And there are convenient methods added to aecu to check bundles and crx package versions

**Comment by gruberrolandvaltech** [comment]
I think putting the constraint in the file name is not a good idea. This will be very hard to read.
Currently, AECU does not provide any methods to check bundle versions or CRX package versions. This would not really match the used builder pattern.
But GroovyConsole itself already has similar methods. Maybe they can add it directly?

Not sure if run modes would help in your case?

Otherwise, you could try to use full qualified class names where you are not sure if the bundle exists. Not sure if this would be executed without ClassNotFoundException.

**Comment by gruberrolandvaltech** [comment]
Ok, so you mean something like this in a folder?

- aecu_prechecks.groovy
- script1.groovy
- script2.groovy
- script3.groovy

aecu_prechecks.groovy would be executed first and only if it does not throw an error the other scripts would be executed.

**Comment by pun-ky** [comment]
Yes but rather per script. Not per folder.

**Comment by gruberrolandvaltech** [comment]
So something like this?

- .prechecks.groovy
- script1.prechecks.groovy
- script1.groovy
- script2.groovy
- script3.groovy

.prechecks.groovy would be the default for the folder. script1.prechecks.groovy would override the default for script1.groovy.

**Comment by pun-ky** [comment]
Yep will be okay but on windows leading dot in filename is problematic😉

**Comment by gruberrolandvaltech** [comment]
Oh, thanks for the hint. :)
Will put the final naming in first post then.

**Comment by gruberrolandvaltech** [comment]
Hi @pun-ky,

sorry that this got deprioritized so long, Is it still an issue or could this also be solved using run modes?

**Comment by pun-ky** [comment]
About contrains I mean that they could check if app is already installed. I cannot do that using runmodes so the origin problem cannot be solved. No worries, it's nice to have it.

**Comment by gruberrolandvaltech** [comment]
Took some time but finally implemented: https://github.com/valtech/aem-easy-content-upgrade/pull/174
