### ISSUE TITLE
Compatibility with Groovy Console 13

### ISSUE THREAD

**Issue by gruberrolandvaltech** [valtech/aem-easy-content-upgrade#88]
* install hook: read scripts in /var/groovyconsole/scripts/aecu
* GUI: read scripts in /var/groovyconsole/scripts/aecu

Areas:
* GUI
* Install hook
* Example package

**Comment by pun-ky** [comment]
when release is planned?

**Comment by gruberrolandvaltech** [comment]
Release was done today :)
