### ISSUE TITLE
Allow Node Creation

### ISSUE THREAD

**Issue by singhal425** [valtech/aem-easy-content-upgrade#89]
It's better to have a feature to allow to create node to avoid doing it via custom action. Because, sometimes, with the template update, it might be possible that a new component is added so a new node should exist under page but that applies only for new pages however, for existing pages, it's required to do write the traditional script or custom action(In ACEU) to accomplish the task.
Having the node creation feature will definitely help to save some time during content migration.

**Comment by gruberrolandvaltech** [comment]
New actions:
doCreateResource(String name, String primaryType)
doCreateResource(String name, String primaryType, Map<String, Object> properties)
doCreateResourceAt(String relativePath, String name, String primaryType)
doCreateResourceAt(String relativePath, String name, String primaryType, Map<String, Object> properties)

**Comment by gruberrolandvaltech** [comment]
PR https://github.com/valtech/aem-easy-content-upgrade/pull/117
