### ISSUE TITLE
Uninstalling bundle package does not remove content properly

### ISSUE THREAD

**Issue by retozigerlig** [valtech/aem-easy-content-upgrade#90]
If you uninstall the bundle package, the sources are not getting removed from the instance. If you install the groovy console and aecu.ui.apps package separately, it is possible to remove all sources by uninstalling the related packages.

**Comment by gruberrolandvaltech** [comment]
You need to uninstall Groovy Console and AECU UI Apps in addition. See also:
https://forums.adobe.com/thread/2545502

We will document the uninstallation process.

**Comment by gruberrolandvaltech** [comment]
PR https://github.com/valtech/aem-easy-content-upgrade/pull/92
